- name: Installs vim
  become: yes
  become_user: root
  package:
    name: vim
    state: present

- name: Link vim bootstrap config
  copy:
    src: vimrc_bootstrap
    dest: "{{ lookup('env', 'HOME') }}/.vimrc"

- name: Install Vim plugins
  shell: | 
    cd {{  lookup('env', 'HOME') }}/.vim/autoload 
    curl -fLo {{  lookup('env', 'HOME') }}/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    /usr/bin/vim +PlugInstall +qall +enter +silent 

- name: Link vim final config
  copy:
    src: vimrc
    dest: "{{ lookup('env', 'HOME') }}/.vimrc"

- name: Configure YCM
  shell: |
    cd {{  lookup('env', 'HOME') }}/.vim/plugged/YouCompleteMe
    python3 install.py --clangd-completer